# Form implementation generated from reading ui file '.\ui\dtc_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(572, 383)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dtc_box = QtWidgets.QWidget(parent=Form)
        self.dtc_box.setObjectName("dtc_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dtc_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.did_title_lbl = QtWidgets.QLabel(parent=self.dtc_box)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.did_title_lbl.setFont(font)
        self.did_title_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.did_title_lbl.setObjectName("did_title_lbl")
        self.verticalLayout.addWidget(self.did_title_lbl)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.read_no_dtc_btn = QtWidgets.QPushButton(parent=self.dtc_box)
        self.read_no_dtc_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.read_no_dtc_btn.setObjectName("read_no_dtc_btn")
        self.gridLayout.addWidget(self.read_no_dtc_btn, 0, 0, 1, 1)
        self.read_single_dtc_btn = QtWidgets.QPushButton(parent=self.dtc_box)
        self.read_single_dtc_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.read_single_dtc_btn.setObjectName("read_single_dtc_btn")
        self.gridLayout.addWidget(self.read_single_dtc_btn, 1, 0, 1, 1)
        self.dtc_no_txt = QtWidgets.QLabel(parent=self.dtc_box)
        self.dtc_no_txt.setText("")
        self.dtc_no_txt.setObjectName("dtc_no_txt")
        self.gridLayout.addWidget(self.dtc_no_txt, 0, 1, 1, 1)
        self.erase_dtc_btn = QtWidgets.QPushButton(parent=self.dtc_box)
        self.erase_dtc_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.erase_dtc_btn.setObjectName("erase_dtc_btn")
        self.gridLayout.addWidget(self.erase_dtc_btn, 2, 0, 1, 1)
        self.erase_dtc_msg_lbl = QtWidgets.QLabel(parent=self.dtc_box)
        self.erase_dtc_msg_lbl.setText("")
        self.erase_dtc_msg_lbl.setObjectName("erase_dtc_msg_lbl")
        self.gridLayout.addWidget(self.erase_dtc_msg_lbl, 2, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dtc_error_tbl = QtWidgets.QTableWidget(parent=self.dtc_box)
        self.dtc_error_tbl.setObjectName("dtc_error_tbl")
        self.dtc_error_tbl.setColumnCount(0)
        self.dtc_error_tbl.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.dtc_error_tbl)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.dtc_box)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.did_title_lbl.setText(_translate("Form", "Diagnostic Trouble Codes (DTC)"))
        self.read_no_dtc_btn.setText(_translate("Form", "Read No. of DTC"))
        self.read_single_dtc_btn.setText(_translate("Form", "Read DTC"))
        self.erase_dtc_btn.setText(_translate("Form", "Erase DTC"))
